### ISSUE TITLE
No image display in WaarpGateway 3.0.4 httpadmin (similar  to Waarp-r66 3.0.4)

### ISSUE THREAD

**Issue by fjudith** [waarp/WaarpGatewayFtp#48]
Hello,

Images are missing when rendering the WaarpGatewayFTP 3.0.4 httpadmin page.

Similar symptoms were fixed in Waarp 3.0.6 by patching to Waarp-R66 3.0.7-beta1.

Tried to copy the img, gre, and res folder from r66-admin to gwftp-admin without success.

**Comment by bcarlin** [comment]
actually, it might have been fixed by waarp/WaarpGatewayKernel#34 ... I'm testing it...
